# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_response_post_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-id']},
        ),
    ]
